Imt2/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Imt2.Models
{
    public class Car
    {
        public int Id { get; set; }
        public int Doors { get; set; }
        public int Seats { get; set; }
        public int Luggage { get; set; }
        public int Transmission { get; set; }
        public int Age { get; set; }
        public int CarModelId { get; set; }
        public Marka Marka { get; set; }

    }


}

Imt2/Models/Marka.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Imt2.Models
{
    public class Marka
    {
        public int Id { get; set; }
        public string CarModel { get; set; }
        public List<Car> cars { get; set; }

    }
}

Imt2/Areas/Manage/Controllers/DasboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Imt2.Areas.Manage.Controllers
{
    [Area("Manage")]
    public class DasboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Imt2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imt2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
    }
}

Imt2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<main>
    <div class="slider">
        <div class="container">
            <div class="title">
                <h1>FIND YOUR RENT A CAR</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="card">
                <div class="formwrap sliderForm">
                    <h3>Search Car</h3>
                    <form>
                        <div class="form-group">
                            <input type="text"
                                   name="location"
                                   class="form-control"
                                   placeholder="Pick up Location" />
                        </div>
                        <div class="form-group">
                            <input type="text"
                                   name="location"
                                   class="form-control"
                                   placeholder="Drop up Location" />
                        </div>
                        <div class="form-group">
                            <input type="text"
                                   name="date"
                                   class="form-control"
                                   placeholder="Pick Date" />
                        </div>
                        <div class="form-group">
                            <input type="text"
                                   name="date"
                                   class="form-control"
                                   placeholder="Drop Date" />
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn" value="Search Now" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="offers">
        <div class="container">
            <h1>OUR BEST OFFERS</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a arcu
                eu justo euismod rutrum. Quisque id enim ac tortor malesuada
                vestibulum non quis turpis. Ut eget ornare arcu. Suspendisse velit
                mi, pulvinar sed mauris eget, efficitur tempor ex.
            </p>
            <div class="col-12">
                <div class="box-container col-4">
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                </div>
                <div class="box-img col-4">
                    <img src="~/assets/img/featureCarImg.png" alt="" />
                </div>
                <div class="box-container col-4">
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                    <div class="box-item">
                        <i class="fa-solid fa-car"></i>
                        <h4>Featured Luxury Cars</h4>
                        <p>
                            Lorem ipsum dolor sit amet, onsectetuer adipiscing elitcommodo
                            ligula eget dolor.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="vehicle">
        <div class="container">
            <h1>VEHICLE MODELS FOR RENT</h1>
            <div class="col-12">
                <div class="info-container col-4">
                    <a href="">
                        <span>Bmw </span>
                        "3series"
                    </a>
                    <a href="">
                        <span>Audi </span>
                        "A1 S-Line"
                    </a>
                    <a href="">
                        <span>Toyota </span>
                        "Camry"
                    </a>
                    <a href="">
                        <span>Mercedes-Benz </span>
                        "GLK"
                    </a>
                    <a href="">
                        <span>Subaro </span>
                        "Imperiza"
                    </a>
                    <a href="">
                        <span>Toyota </span>
                        "Corolla"
                    </a>
                    <a href="">
                        <span>Subaro </span>
                        "Imperiza"
                    </a>
                </div>
                <div class="cars col-8">
                    <div class="row">
                        <div class="col-4 menu-img1">
                            <img src="~/assets/img/bmw.webp" class=" menu-img  active" alt="" />
                            <img src="~/assets/img/audi-a3-s-line-1.avif"
                                 class="menu-img"
                                 alt="" />
                            <img src="~/assets/img/download.jpg" class="  menu-img  " alt="" />
                            <img src="~/assets/img/download (1).jpg"
                                 class="menu-img"
                                 alt="" />
                            <img src="~/assets/img/1200px-Washauto06_subaru_impreza.jpg"
                                 class="menu-img"
                                 alt="" />
                            <img src="~/assets/img/2.webp" class=" menu-img " alt="" />
                            <img src="~/assets/img/2.webp" class="menu-img " alt="" />
                            <img src="~/assets/img/bmw.webp" class="  menu-img " alt="" />
                        </div>
                        <div class="col-8">
                            <ul class="cars-menu">
                                <li class="menu-item active" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                                <li class="menu-item" data-target="#tab1">
                                    <span>$ 37.40 </span>
                                    Model&nbsp;&nbsp;&nbsp;&nbsp;Limousine
                                    Doors&nbsp;&nbsp;&nbsp;&nbsp;4
                                    Seats&nbsp;&nbsp;&nbsp;&nbsp;5
                                    Luggage&nbsp;&nbsp;&nbsp;&nbsp;2 Suitcases / 2 Bags
                                    Transmission&nbsp;&nbsp;&nbsp;&nbsp;Automatic Air
                                    conditioning&nbsp;&nbsp;&nbsp;&nbsp;Yes Minimum
                                    age&nbsp;&nbsp;&nbsp;&nbsp;25 years
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="maps-container">

        <div class="col-12">
            <div class=" maps  col-6">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48954.595504120494!2d48.88555377910156!3d39.92657470000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x403b05fba1454cb7%3A0x4b9faea74fb9c800!2sShirvan%2C%20Azerbaijan!5e0!3m2!1sen!2s!4v1655130040170!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="form col-6">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput">
                    <label for="floatingInput">Enter Name</label>
                </div>
                <div class="form-floating">
                    <input type="email" class="form-control" id="Email">
                    <label for="floatingPassword">Email</label>
                </div>
                <div class="form-floating">
                    <input type="text" class="form-control" id="Phone">
                    <label for="">Phone</label>
                </div>
                <textarea placeholder="Comments" name="Comments" id="" cols="30" rows="10"></textarea>

            </div>

        </div>

    </div>

</main>

Imt2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />
    <!-- FontAvesome -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <!-- Css -->
    <link rel="stylesheet" href="~/assets/css/main.css" />
</head>
<body>
    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="./assets/img/logo.png" alt="" />
                </a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Dasboard" asp-action="Index" asp-area="Manage">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Servis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Vehicles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Supports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer>

        <i class="fa-brands fa-facebook"></i>
        <i class="fa-brands fa-facebook"></i>
        <i class="fa-brands fa-facebook"></i>
        <i class="fa-brands fa-facebook"></i>
        <span>©Copyright 2019 Rent A Car. All Rights Reserved</span>

    </footer>
    <script src="~/assets/js/main.js"></script>
</body>
</html>